[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.6",
    "numpy>=2.3.3",
    "pandas>=2.3.3",
    "psutil>=7.1.0",
    "requests>=2.32.5",
]
